---

# yamllint disable rule:line-length

name: publish draft releases

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches: [manta]
  push:
    branches: [ghzlatarev/better-rtu-parsing]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  AWS_INSTANCE_SSH_PUBLIC_KEY: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPb24HEQ++aNFWaqVyMtIs6GotUB8R+q61XOoI2z6uMj
  AWS_REGION: us-east-1
  AWS_SUBNET_ID: subnet-08c26caf0a52b7c19
  AWS_SECURITY_GROUP_ID: sg-0315bffea9042ac9b
  AWS_INSTANCE_TYPE: c5a.8xlarge  # 32 vcpu, 64gb ram, $1.392 hourly
  AWS_INSTANCE_ROOT_VOLUME_SIZE: 32
  AWS_IMAGE_SEARCH_PATTERN: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
  AWS_IMAGE_SEARCH_OWNERS: '["099720109477"]'  # canonical

jobs:

  parse-runtimes:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        runtime:
          -
            name: calamari
          -
            name: manta
    outputs:
      calamari-runtime-current: ${{ steps.get-runtime-current.outputs.calamari-runtime-current }}
      calamari-runtime-base: ${{ steps.get-runtime-base.outputs.calamari-runtime-base }}
      manta-runtime-current: ${{ steps.get-runtime-current.outputs.manta-runtime-current }}
      manta-runtime-base: ${{ steps.get-runtime-base.outputs.manta-runtime-base }}
    steps:
      -
        uses: actions/checkout@v2
      -
        name: ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      -
        name: get ${{ matrix.runtime.name }} runtime version current
        id: get-runtime-current
        run: |
          runtime_current="$(ruby -e '
            require "./scripts/github/lib.rb";
            puts get_runtime("${{ matrix.runtime.name }}")
          ')"
          echo "::set-output name=${{ matrix.runtime.name }}-runtime-current::$runtime_current"
          echo ....................
      -
        name: get ${{ matrix.runtime.name }} runtime version base
        id: get-runtime-base
        run: |
          mkdir temp_for_run
          cd temp_for_run
          git clone -b manta https://github.com/Manta-Network/Manta.git
          cd Manta
          runtime_base="$(ruby -e '
            require "./scripts/github/lib.rb";
            puts get_runtime("${{ matrix.runtime.name }}")
          ')"
          echo "::set-output name=${{ matrix.runtime.name }}-runtime-base::$runtime_base"
          echo ....................

  check-for-runtime-upgrade:
    needs:
      - parse-runtimes
    runs-on: ubuntu-20.04
    outputs:
      do-versions-match: ${{ steps.check-match.outputs.match }}
      old_version: ${{ needs.parse-runtimes.old_version }}
    steps:
      -
        name: check if runtime versions match
        id: check-match
        run: |
          echo "${{ needs.parse-runtimes.outputs.calamari-runtime-current }}"
          echo "test me"
          echo "::set-output name=match::true"
          if [[ ${{ needs.parse-runtimes.outputs.manta-runtime-base }} != ${{ needs.parse-runtimes.outputs.manta-runtime-current }} ]]; then echo "::set-output name=match::false"; fi
          if [[ ${{ needs.parse-runtimes.outputs.calamari-runtime-base }} != ${{ needs.parse-runtimes.outputs.calamari-runtime-current }} ]]; then echo "::set-output name=match::false"; fi
      -
        name: force fail if new versions don't match
        run: |
          if [[  ${{ needs.parse-runtimes.outputs.manta-runtime-current }} !=  ${{ needs.parse-runtimes.outputs.calamari-runtime-current }} ]]; then exit 1; fi

# yamllint enable rule:line-length
