---
name: publish draft releases

on:
  push:
    branches:
      - manta-pc

env:
  CARGO_TERM_COLOR: always

jobs:

  get-rust-versions:
    runs-on: ubuntu-latest
    container:
      image: paritytech/ci-linux:production
    outputs:
      rustc-stable: ${{ steps.get-rust-versions.outputs.stable }}
      rustc-nightly: ${{ steps.get-rust-versions.outputs.nightly }}
    steps:
      -
        id: get-rust-versions
        run: |
          echo "::set-output name=stable::$(rustc +stable --version)"
          echo "::set-output name=nightly::$(rustc +nightly --version)"

  build-runtimes:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime:
          - calamari
          - manta-pc
    steps:
      - uses: actions/checkout@v2
      - name: cache target dir
        uses: actions/cache@v2
        with:
          path: "${{ github.workspace }}/runtime/${{ matrix.runtime }}/target"
          key: srtool-target-${{ matrix.runtime }}-${{ github.sha }}
          restore-keys: |
            srtool-target-${{ matrix.runtime }}-
            srtool-target-
      - name: build ${{ matrix.runtime }} runtime
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          image: paritytech/srtool
          chain: ${{ matrix.runtime }}
      - name: persist srtool digest
        run: >
          echo '${{ steps.srtool_build.outputs.json }}' |
          jq > ${{ matrix.runtime }}_srtool_output.json
      - name: upload ${{ matrix.runtime }} srtool json
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime }}-srtool-json
          path: ${{ matrix.runtime }}_srtool_output.json
      - name: upload ${{ matrix.runtime }} runtime
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.runtime }}-runtime
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}

  build-changelog:
    runs-on: ubuntu-latest
    needs:
      - get-rust-versions
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: Manta
      - name: ruby setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: changelog gems
        run: |
          gem install changelogerator git toml
      - name: generate changelog
        env:
          RUSTC_STABLE: ${{ needs.get-rust-versions.outputs.rustc-stable }}
          RUSTC_NIGHTLY: ${{ needs.get-rust-versions.outputs.rustc-nightly }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          ruby $GITHUB_WORKSPACE/Manta/scripts/github/generate-changelog.rb |
          tee changelog.md
      - name: upload changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: |
            changelog.md
